Repository pmix/pmix-standard, pull requests merged in 2020-12, with the labels that each got.

#308 Clarify the PMIx_Abort behavior
  Chap_API_Proc_Mgmt.tex
  Chap_API_Server.tex
  Chap_API_Struct.tex
  Chap_Revisions.tex
Labels: Clarification

#310 Cleanup deprecated and removed entries in index
  Chap_API_Proc_Mgmt.tex
  Chap_API_Security.tex
  Chap_API_Server.tex
  Chap_API_Struct.tex
  Chap_API_Sync_Access.tex
  Chap_API_Tools.tex
  Chap_Revisions.tex
  bin/check-attr-refs.py
  bin/check-multi-declare.py
  pmix.sty
Labels: Editorial

#314 Fixup Python bindings to match C bindings
  App_Python.tex
  Chap_API_Server.tex
Labels: Correction

#312 Fix watermark generation on newer latex installs
  pmix-standard.tex
Labels: Editorial

#315 Update tools chapter
  Chap_API_Struct.tex
  Chap_API_Tools.tex
  Chap_Revisions.tex
Labels: Clarification

#322 Add a directive indicating that a reqd attribute has been processed
  Chap_API_Server.tex
  Chap_API_Struct.tex
  Chap_Revisions.tex
Labels: Clarification

#323 Update master to track v4
  Chap_API_Server.tex
  Chap_API_Struct.tex
  Chap_Revisions.tex
Labels: Clarification
