Repository pmix/pmix-standard, pull requests merged in 2020-08, with the labels that each got.

#263 Add a 'make check-decl' to check for multiple declarations
  Makefile
  bin/check-multi-declare.py
Labels: enhancement

#268 Improve reference checker at the end of make
  Chap_Introduction.tex
  Makefile
  bin/check-doc.sh
  pmix-standard.tex
Labels: WorkInProgress

#267 Updates to complete PMIx v4
  Acknowledgements.tex
  App_Python.tex
  Chap_API_Data_Mgmt.tex
  Chap_API_Event.tex
  Chap_API_Fabric.tex
  Chap_API_Init.tex
  Chap_API_Job_Mgmt.tex
  Chap_API_Key_Value_Mgmt.tex
  Chap_API_NonReserved_Keys.tex
  Chap_API_Proc_Mgmt.tex
  Chap_API_Publish.tex
  Chap_API_Reserved_Keys.tex
  Chap_API_Security.tex
  Chap_API_Server.tex
  Chap_API_Sets_Groups.tex
  Chap_API_Struct.tex
  Chap_API_Sync_Access.tex
  Chap_API_Tools.tex
  Chap_Introduction.tex
  Chap_Revisions.tex
  Chap_Terms.tex
  Makefile
  TitlePage.tex
  figs/nodeinfo.pdf
  figs/procinfo.pdf
  pmix-standard.tex
  pmix.sty
Labels: RFC
