Repository pmix/pmix-standard, pull requests merged in 2021-07, with the labels that each got.

#353 v4: Increment to v4.1 as next target
  pmix-standard.tex
Labels: Editorial

#349 MPI Sessions Use-case
  App_Use_Cases.tex
  figs/mpi-sessions1.png
Labels: Accepted as Stable, Eligible, First Vote Passed, RFC

#327 Clarify three roles of consumers of the PMIx interface
  Chap_Introduction.tex
Labels: Accepted as Stable, Eligible, First Vote Passed, RFC

#347 Issue 175 chapter 2 master
  Chap_Terms.tex
Labels: Accepted as Stable, Eligible, First Vote Passed, Major Text Change, RFC
