Repository pmix/pmix-standard, pull requests merged in 2021-11, with the labels that each got.

#355 Fix cut/paste issue with PMIX_DATA_ARRAY_DESTRUCT.
  Chap_API_Struct.tex
Labels: Correction, RFC, Eligible, First Vote Passed, Errata

#368 Fix cut/paste issue with PMIX_DATA_ARRAY_DESTRUCT.
  Chap_API_Struct.tex
Labels: Editorial, Errata

#350 Return codes
  Chap_API_Data_Mgmt.tex
  Chap_API_Event.tex
  Chap_API_Fabric.tex
  Chap_API_Init.tex
  Chap_API_Job_Mgmt.tex
  Chap_API_NonReserved_Keys.tex
  Chap_API_Proc_Mgmt.tex
  Chap_API_Publish.tex
  Chap_API_Security.tex
  Chap_API_Server.tex
  Chap_API_Sets_Groups.tex
  Chap_API_Struct.tex
  Chap_API_Sync_Access.tex
  Chap_API_Tools.tex
  pmix.sty
Labels: Clarification, Eligible, First Vote Passed, Accepted as Stable, Major Text Change
