Repository pmix/pmix-standard, pull requests merged in 2021-05, with the labels that each got.

#328 Add appendix with use case descriptions
  App_Use_Cases.tex
  Chap_API_Data_Mgmt.tex
  Chap_API_Event.tex
  Chap_API_Fabric.tex
  Chap_API_Init.tex
  Chap_API_Job_Mgmt.tex
  Chap_API_NonReserved_Keys.tex
  Chap_API_Proc_Mgmt.tex
  Chap_API_Publish.tex
  Chap_API_Security.tex
  Chap_API_Server.tex
  Chap_API_Sets_Groups.tex
  Chap_API_Struct.tex
  Chap_API_Sync_Access.tex
  Chap_API_Tools.tex
  Makefile
  bin/check-multi-declare.py
  bin/convert-to-copysig.py
  figs/direct-launch.jpg
  figs/indirect-launch.jpg
  figs/process-acquisition.jpg
  pmix-standard.bib
  pmix-standard.tex
  pmix.sty
  sources/.clang-format
  sources/hybrid-prog-model.c
Labels: Accepted as Stable, Eligible, First Vote Passed, RFC

#325 Remove stale language and roll to v4.1
  Chap_API_Event.tex
Labels: Eligible, Errata, First Vote Passed, RFC

#332 Add four missing data management functions
  Chap_API_Data_Mgmt.tex
Labels: Accepted as Provisional, Eligible, RFC

#331 Add a few simple, but helpful macros
  Chap_API_Struct.tex
Labels: Accepted as Provisional, Eligible, RFC

#334 Add a data type constant for pmix_nspace_t
  Chap_API_Struct.tex
Labels: Accepted as Provisional, Eligible, RFC

#351 Cherry-pick of v4 Provisional and Errata
  Chap_API_Data_Mgmt.tex
  Chap_API_Event.tex
  Chap_API_Struct.tex
  pmix.sty
Labels: Editorial
