Repository pmix/pmix-standard, pull requests merged in 2021-03, with the labels that each got.

#337 Add Provisional Markers
  pmix.sty
Labels: Editorial

#338 Add Provisional Markers
  pmix.sty
Labels: Editorial

#340 Move from Travis to GitHub Actions
  .github/workflows/build-ci.yml
  .travis.yml
Labels: Editorial

#343 Move from Travis to GitHub Actions
  .github/workflows/build-ci.yml
  .travis.yml
Labels: Editorial

#280 Storage system query support
  Chap_API_Storage.tex
  Makefile
  pmix-standard.tex
Labels: Accepted as Provisional, Eligible, RFC

#345 Add provisional markers to storage chapter
  Chap_API_Storage.tex
  Chap_Revisions.tex
Labels: Editorial

#346 Storage Chapter: Provisional
  Chap_API_Storage.tex
  Chap_Revisions.tex
  Makefile
  pmix-standard.tex
Labels: Accepted as Provisional, Editorial
