Repository pmix/pmix-standard, pull requests merged in 2022-05, with the labels that each got.

#382 Touch up debugger attributes and constants
  Chap_API_Tools.tex
  Chap_Revisions.tex
Labels: RFC, Eligible, First Vote Passed, Accepted as Stable

#383 Convert several macros to APIs
  App_Python.tex
  Chap_API_Proc_Mgmt.tex
  Chap_API_Reserved_Keys.tex
  Chap_API_Server.tex
  Chap_API_Struct.tex
  Chap_Revisions.tex
  pmix.sty
Labels: RFC, Eligible, First Vote Passed, Accepted as Stable

#403 Sync v4 to master
  App_Python.tex
  App_Use_Cases.tex
  Chap_API_Proc_Mgmt.tex
  Chap_API_Reserved_Keys.tex
  Chap_API_Server.tex
  Chap_API_Struct.tex
  Chap_API_Tools.tex
  Chap_Revisions.tex
  pmix.sty
Labels: Editorial

#405 Issue 175: Sharing basics -rebased on master
  Chap_API_Fabric.tex
  Chap_API_NonReserved_Keys.tex
  Chap_API_Publish.tex
  Chap_API_Reserved_Keys.tex
  Chap_API_Server.tex
  Chap_API_Sync_Access.tex
  Makefile
  pmix-standard.tex
Labels: Accepted as Stable, Editorial

#406 Issue 175: Updates to presentation of Reserved_Keys chapter -rebased on master
  Chap_API_Fabric.tex
  Chap_API_Reserved_Keys.tex
Labels: Accepted as Stable, Editorial

#408 Issue 175 make sync chap 2commits -rebased on master
  Chap_API_Sharing_Basics.tex
  Chap_API_Sync.tex
  Makefile
  pmix-standard.tex
Labels: Accepted as Stable, Editorial

#410 A few Infrastructure fixes
  .github/workflows/build-main.yml
  .gitignore
  Makefile
  README.md
  bin/check-attr-refs.py
  bin/check-multi-declare.py
  bin/check-openpmix.py
  bin/convert-to-copysig.py
  bin/display-stats.py
  bin/process-example.py
Labels: Editorial
