Repository pmix/pmix-standard, pull requests merged in 2022-03, with the labels that each got.

#376 Issue 373 - Define when PMIX_PARENT_ID is set and add definition for tool
  Chap_API_Reserved_Keys.tex
  Chap_Terms.tex
Labels: RFC, Eligible, First Vote Passed, Errata

#377 Issue-372 Clarify PMIX_CMD_LINE in spawn case.
  Chap_API_Reserved_Keys.tex
Labels: Clarification, RFC, Eligible, First Vote Passed, Errata

#359 Assign specific values to PMIx constants
  Chap_API_Event.tex
  Chap_API_Fabric.tex
  Chap_API_Init.tex
  Chap_API_Job_Mgmt.tex
  Chap_API_NonReserved_Keys.tex
  Chap_API_Proc_Mgmt.tex
  Chap_API_Publish.tex
  Chap_API_Server.tex
  Chap_API_Sets_Groups.tex
  Chap_API_Storage.tex
  Chap_API_Struct.tex
  Chap_API_Sync_Access.tex
  Chap_API_Tools.tex
  Chap_Revisions.tex
  pmix.sty
Labels: RFC, Eligible, First Vote Passed, Accepted as Stable

#357 Use Case: Cross-Version Support
  App_Use_Cases.tex
  Chap_API_Server.tex
Labels: Use Case, Eligible, First Vote Passed, Accepted as Stable

#385 Provide static initializers for PMIx structs
  Chap_API_Data_Mgmt.tex
  Chap_API_Fabric.tex
  Chap_API_Proc_Mgmt.tex
  Chap_API_Publish.tex
  Chap_API_Server.tex
  Chap_API_Struct.tex
  Chap_API_Sync_Access.tex
Labels: RFC, Accepted as Provisional, Eligible

#384 Add some missing attributes and one API for server support
  Chap_API_Data_Mgmt.tex
  Chap_API_Proc_Mgmt.tex
  Chap_API_Reserved_Keys.tex
  Chap_API_Server.tex
  Chap_API_Sync_Access.tex
Labels: RFC, Accepted as Provisional, Eligible

#380 Add several IOF attributes
  Chap_API_Server.tex
  Chap_API_Tools.tex
  Chap_Revisions.tex
Labels: RFC, Accepted as Provisional, Eligible
