Repository pmix/pmix-standard, pull requests merged in 2024-03, with the labels that each got.

#503 Issue421/pmix iof cbfunc arg type@v4
  Chap_API_Server.tex
Labels: Editorial

#490 Issue 414: ordering & method of specifying procs in collectives clarified
  Chap_API_Proc_Mgmt.tex
  Chap_API_Sets_Groups.tex
  Chap_API_Sync.tex
Labels: RFC, Accepted as Provisional, Eligible, First Vote Passed

#484 How to implement pmix_server_dmodex_req_fn_t when PMIX_REQUIRED_KEY set
  Chap_API_Server.tex
Labels: Clarification, RFC, Accepted as Provisional, Eligible, First Vote Passed
